version: '3.3'
services:
  bid-taxi-service:
    container_name: bid-taxi-service
    image: bid-taxi-service:latest
    environment:
      - PORT=3030
      - NODE_ENV=default
    restart: always
    build: .
    ports:
      - "3030:3030"
    links:
      - mongo
  mongo:
    container_name: mongo_db
    restart: always
    logging:
      options:
        max-size: 1g
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
