version: '3.3'
services:
  login-app:
    container_name: bid-taxi-service
    image: latest/bid-taxi-service
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo_db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: admin
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
