version: "3.8"
services:
  mongo:
    container_name: mongo_db
    restart: always
    logging:
      options:
        max-size: 1g
    image: mongo
    ports:
      - '27017:27017'
    networks:
      bid-taxi-service:

networks:
  bid-taxi-service:
    name: bid-taxi-service-network
    driver: bridge






